### ISSUE TITLE
Cave Enhancements with Terralith

### ISSUE THREAD

**Issue by Khytwel** [ExDrill/CaveEnhancementsMod#8]
Hi,

Would it be possible to make Cave Enhancements compatible with Terralith so that your cave biomes can be generated?

Cave Enhancements 1.1.1
Terralith v2.2.1a

**Comment by ExDrill** [comment]
Hello, I've actually recently found out a way for these 2 to have compatibility, if you use terrablender and also a mod that uses terrablender (for example: Oh the Biomes You'll Go, Graveyard Biomes). You can find the biomes. This is because of how terrablender's regions work and how Cave Enhancements loads it's biomes into the game. There isn't true compatibility but I was trying to work on that but Starmute hasn't responded to me...

**Comment by outercloudstudio** [comment]
I think the best bet here would be to create a compatibility branch that uses terrablender instead of the biome system we have now. I'll look into that later today.

**Comment by ExDrill** [comment]
This should be fixed by the next update, as we're adding in a lot of compatibility with other mods.
